name: 机场订阅转换

on:
  push:
    branches:
      - main  # 可以根据你的需求修改分支名称
      
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Data
        run: |
          curl -o test.yaml https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fpqjc.site%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D2a07deed699a160eabdaca539e050d14%26flag%3Dclash-meta&target=clash
