name: 机场订阅转换

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.MY_SUB_URL }}

jobs:
  request:
    runs-on: ubuntu-latest
    steps:

      - name: Use variables
        run: |
          echo "variable from shell environment  : $env_var"

      - name: Run URL encoding
        run: |
          echo "Input: $env_var"
          ENCODED_VALUE=$(node -e "console.log(encodeURIComponent('$env_var'))")
          echo "Encoded: $ENCODED_VALUE"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Data
        run: |
          curl -o test.yaml "https://proxy-provider-converter.vercel.app/api/convert?url=$env_var"

      - name: Commit Changes
        run: |
          git config --global user.name "action bot"
          git config --global user.email "test@gmail.com"
          git add test.yaml
          git commit -m "Update test.yaml"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
