name: 机场订阅转换

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */3 * * *"

jobs:
  request:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Data
        run: |
          echo "Input: ${{ vars.MY_SUB_URL }}"
          ENCODED_VALUE=$(node -e "console.log(encodeURIComponent('${{ vars.MY_SUB_URL }}'))")
          echo "Encoded: $ENCODED_VALUE"
          curl -o test.yaml "https://proxy-provider-converter.vercel.app/api/convert?url=$ENCODED_VALUE"

      - name: Commit Changes
        run: |
          git config --global user.name "action bot"
          git config --global user.email "test@gmail.com"
          git add test.yaml
          git commit -m "Update test.yaml"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
